CREATE TABLE IF NOT EXISTS cotations (
		id INTEGER PRIMARY KEY AUTO_INCREMENT,
		code VARCHAR(255) NOT NULL,
		codein VARCHAR(255) NOT NULL,
		bid VARCHAR(255) NOT NULL,
		ask VARCHAR(255) NOT NULL,
		create_date VARCHAR(255) NOT NULL

)